Models/PersonModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace nombusoStudyGroup.Models
{
	public class PersonModel
	{
        [Display(Name = "Student Number")]
        public int StudentNumber { get; set; }
        
        [Display(Name = "First Name")]
        public string Name { get; set; }
        
        [Display(Name = "Surname")]
        public string Surname { get; set; }

        [Display(Name = "Email")]
        public string Email { get; set; }

        [Display(Name = "Link")]
        public string myLink { get; set; }

        [Display(Name = "Delete")]
        public string myDelete { get; set; }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace nombusoStudyGroup.Controllers
{
    public class HomeController : Controller
    {
        
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/PeopleController.cs
using System.Collections.Generic;
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using nombusoStudyGroup.Models;


namespace nombusoStudyGroup.Controllers
{
    public class PeopleController : Controller
    {
        // GET: People
        public ActionResult ListPeople()
        {
            List<Models.PersonModel> people = new List<Models.PersonModel>();

            people.Add(new Models.PersonModel { StudentNumber = 12345, Name = "Nombuso", Surname = "Mdletshe", Email = "nombuso.mdletshe@tuks.co.za", myLink = "~\\Content\\HTML\\Nombuso.html" });
            people.Add(new Models.PersonModel { StudentNumber = 12348, Name = "Laska", Surname = "Mdletshe", Email = "laska.mdletshe@tuks.co.za", myLink = "~\\Content\\HTML\\Laska.html" });
            people.Add(new Models.PersonModel { StudentNumber = 12346, Name = "Mbalenhle", Surname = "Mdletshe", Email = "mbalenhle.mdletshe@tuks.co.za", myLink = "~\\Content\\HTML\\Mbalenhle.html" });
            people.Add(new Models.PersonModel { StudentNumber = 12347, Name = "Nothando", Surname = "Mdletshe", Email = "nothando.mdletshe@tuks.co.za", myLink = "~\\Content\\HTML/Nothando.html" });
            people.Add(new Models.PersonModel { StudentNumber = 12349, Name = "Lola", Surname = "Mdletshe", Email = "lola.mdletshe@tuks.co.za", myLink = "~\\Content\\HTML\\Lola.html" });


            return View(people);
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>
<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@*  Here is this property and assign it this value
    Grab anything you want to grab
    Put any property in the viewbag as much as we want
    Such as Viewbag.Whatever = "Foo";
*@


@{
    ViewBag.Title = "Home Page";
    //ViewBag.Whatever = "Foo"; >> Not being used now. The view collection called "Foo"
    //is not being used or called.

}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>




<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
        <div class="col-md-4">
            <h2>Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </div>
    </div>
    @* IF you have......This will be rendered after "RenderSection in _Layout.cshtml *@
    @* @section Scripts{
        <script type="text/javascript">
            $.....
        </script>
        }
    *@

Views/Home/Notes.cshtml
@{
    ViewBag.Title = "Notes";
}

<h2>Notes</h2>

<img src="@Url.Content("~/ADDITIONAL/mvcgetset.jpg")" />

Views/People/ListPeople.cshtml
@* Interface Enumarable = Enumarate or list (to ascertain the number of : count) *@

@model IEnumerable<nombusoStudyGroup.Models.PersonModel>

@{
    ViewBag.Title = "List of People";
}

<style>
    body {
        background-color: floralwhite;
    }
</style>

<h2>List of People</h2>

@*<p>
        @Html.ActionLink("Create New", "Create") >> In this overload it is the name and the action >> Link going nowhere.
    </p>*@
<table class="people_table" style="color: hotpink; background-color: floralwhite;">
    <tr>
        <th style="background-color:floralwhite;">
            @Html.DisplayNameFor(model => model.StudentNumber)
        </th>
        <th style="background-color:floralwhite;">
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th style="background-color:floralwhite;">
            @Html.DisplayNameFor(model => model.Surname)
        </th>
        <th style="background-color:floralwhite;">
            @Html.DisplayNameFor(model => model.Email)
        <th style="background-color:floralwhite;">
            @Html.DisplayNameFor(model => model.myLink)
        </th>
        <th style="background-color:floralwhite;">
            @Html.DisplayNameFor(model => model.myDelete)
        </th>
    </tr>

    @foreach (var item in Model) //For each person
    {

        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StudentNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                <a href="@Url.Content(item.myLink)" target="_blank" class="btn btn-primary">Link</a>
            </td>
            <td>
            <button class="btn btn-primary delete-button" onclick="delete_row(this)">Delete</button>
            </td>
           

        </tr>
    }
</table>

<script>
    // Delete ROW on button click
    // Delete remove the row that contains the clicked button
    document.querySelectorAll(".delete-button").forEach(button => {
        button.addEventListener("click", function () {
            const row = this.closest("tr");
            row.remove();
        });
    });

    // Highlight rows where first name starts with "N"
    document.querySelectorAll("tbody tr").forEach(row => {
        const firstName = row.children[1].textContent.trim();
        if (firstName.startsWith("N")) {
            row.style.color = "red";
        }
    });
</script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="/Content/Styling.css" rel="stylesheet" />
</head>
<body style="color: hotpink; background-color: floralwhite;" >
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Simple Starting Page", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>
                        <div class="dropdown">
                            <button class="btn btn-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                List of People
                            </button>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="/People/ListPeople">Complete List of People</a></li>
                                <li><a class="dropdown-item" href="~/Content/HTML/Nombuso.html">Nombuso</a></li>
                                <li><a class="dropdown-item" href="~/Content/HTML/Laska.html">Laska</a></li>
                                <li><a class="dropdown-item" href="~/Content/HTML/Mbalenhle.html">Mbalenhle</a></li>
                                <li><a class="dropdown-item" href="~/Content/HTML/Nothando.html">Nothando</a></li>
                                <li><a class="dropdown-item" href="~/Content/HTML/Lola.html">Lola</a></li>
                            </ul>
                        </div>
                    </li>

                    @*<li>@Html.ActionLink("List of People", "People", "ListPeople", new { area = "" }, new { @class = "nav-link" })</li>*@
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/bootstrap.bundle.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>